/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MessageRouteImport } from './routes/message'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UrlRouteImport } from './routes/url'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAnalyzeMessageRouteImport } from './routes/api/analyze.message'
import { Route as ApiAnalyzeUrlRouteImport } from './routes/api/analyze.url'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageRoute = MessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlRoute = UrlRouteImport.update({
  id: '/url',
  path: '/url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeMessageRoute = ApiAnalyzeMessageRouteImport.update({
  id: '/api/analyze/message',
  path: '/api/analyze/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeUrlRoute = ApiAnalyzeUrlRouteImport.update({
  id: '/api/analyze/url',
  path: '/api/analyze/url',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/message': typeof MessageRoute
  '/settings': typeof SettingsRoute
  '/url': typeof UrlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/analyze/message': typeof ApiAnalyzeMessageRoute
  '/api/analyze/url': typeof ApiAnalyzeUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/message': typeof MessageRoute
  '/settings': typeof SettingsRoute
  '/url': typeof UrlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/analyze/message': typeof ApiAnalyzeMessageRoute
  '/api/analyze/url': typeof ApiAnalyzeUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/message': typeof MessageRoute
  '/settings': typeof SettingsRoute
  '/url': typeof UrlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/analyze/message': typeof ApiAnalyzeMessageRoute
  '/api/analyze/url': typeof ApiAnalyzeUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/history'
    | '/message'
    | '/settings'
    | '/url'
    | '/api/health'
    | '/api/analyze/message'
    | '/api/analyze/url'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/history'
    | '/message'
    | '/settings'
    | '/url'
    | '/api/health'
    | '/api/analyze/message'
    | '/api/analyze/url'
  id:
    | '__root__'
    | '/'
    | '/guide'
    | '/history'
    | '/message'
    | '/settings'
    | '/url'
    | '/api/health'
    | '/api/analyze/message'
    | '/api/analyze/url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRoute
  HistoryRoute: typeof HistoryRoute
  MessageRoute: typeof MessageRoute
  SettingsRoute: typeof SettingsRoute
  UrlRoute: typeof UrlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAnalyzeMessageRoute: typeof ApiAnalyzeMessageRoute
  ApiAnalyzeUrlRoute: typeof ApiAnalyzeUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url': {
      id: '/url'
      path: '/url'
      fullPath: '/url'
      preLoaderRoute: typeof UrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/message': {
      id: '/api/analyze/message'
      path: '/api/analyze/message'
      fullPath: '/api/analyze/message'
      preLoaderRoute: typeof ApiAnalyzeMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/url': {
      id: '/api/analyze/url'
      path: '/api/analyze/url'
      fullPath: '/api/analyze/url'
      preLoaderRoute: typeof ApiAnalyzeUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRoute,
  HistoryRoute: HistoryRoute,
  MessageRoute: MessageRoute,
  SettingsRoute: SettingsRoute,
  UrlRoute: UrlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAnalyzeMessageRoute: ApiAnalyzeMessageRoute,
  ApiAnalyzeUrlRoute: ApiAnalyzeUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
